config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'welcome#index'
  get '/settings', to: 'welcome#settings'

  get '/customer_login', to: 'sessions#customer_login_page'
  post '/customer_login', to: 'sessions#customer_login'
  get '/admin_login', to: 'sessions#admin_login_page'
  post '/admin_login', to: 'sessions#admin_login'
  delete '/logout', to: 'sessions#destroy'

  resources :customers, only: %i(index new create) do
    resources :readings, only: %i(index new create)
  end

  resources :admins, only: %i(index)

  namespace :admin do
    resources :customers, only: %i(index show update) do
      post '/invoice', to: "customers#mail"
      resources :readings, only: %i(index new create)
    end
    resources :addresses, only: %i(index new create)
    resources :prices, only: %i(new create)
  end

  root 'welcome#index'
end

app/models/reading.rb
class Reading < ApplicationRecord
  belongs_to :customer
  belongs_to :read_by, polymorphic: true

  validates :reading, presence: true, numericality: { greater_than_or_equal_to: :previous_reading }

  private

  def previous_reading
    previous = Reading.where(customer_id: customer_id).last
    previous.nil? ? 0 : previous.reading
  end
end

app/controllers/admin/readings_controller.rb
class Admin::ReadingsController < AdminsController
  before_action :find_customer
  before_action :find_all_readings, only: %i(index new)

  def index; end

  def new
    @newest_read = Reading.where(customer: @customer).last.reading || 0
    @reading = Reading.new
  end

  def create
    @admin ||= current_admin
    @reading = Reading.new(
      reading: reading_params[:reading].to_d,
      read_by: @admin,
      customer: @customer
    )

    flash[:error] = BuildErrorMessage.new(@reading).call unless @reading.save
    redirect_to admin_customer_readings_url
  end

  private

  def reading_params
    params.require(:reading).permit(:reading, :admin, :customer)
  end

  def find_customer
    @customer = Customer.find(params[:customer_id])
  end

  def find_all_readings
    @readings = Reading.where(customer: @customer)
  end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  before_action :require_login, :find_customer
  before_action :find_all_readings, only: %i(index new)

  def index; end

  def new
    @newest_read = Reading.where(customer: @customer).last.reading || 0
    @reading = Reading.new
  end

  def create
    @reading = Reading.new(
      reading: reading_params[:reading].to_d,
      read_by: @customer,
      customer: @customer
    )

    flash[:error] = BuildErrorMessage.new(@reading).call unless @reading.save
    redirect_to customer_readings_url
  end

  private

  def require_login
    unless customer_logged_in?
      flash[:error] = 'Not logged in.'
      redirect_to root_url
    end
  end

  def reading_params
    params.require(:reading).permit(:reading, :customer)
  end

  def find_customer
    @customer = Customer.find(params[:customer_id])
  end

  def find_all_readings
    @readings = Reading.where(customer: @customer)
  end
end

app/views/readings/_reading_table.html.erb
<table>
  <tr>
    <th>Reading ID</th>
    <th>Reading</th>
    <th>Read By</th>
    <th>Read By ID</th>
    <th>Date Entered</th>
  </tr>
  <% readings.each do |reading| %>
    <tr>
      <td><%= reading.id %></td>
      <td><%= number_with_precision(reading.reading, precision: @customer.address.meter_decimal_places) %></td>
      <td><%= reading.read_by_type %></td>
      <td><%= reading.read_by_id %></td>
      <td><%= reading.created_at %></td>
    </tr>
  <% end %>
  <% unless current_page?(action: :new) %>
    <tr>
      <td></td>
      <td>
        <% if admin_logged_in? %>
          <%= link_to 'New Reading', new_admin_customer_reading_path(customer) %>
        <% else %>
          <%= link_to 'New Reading', new_customer_reading_path(customer) %>
        <% end %>
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  <% end %>
</table>

app/views/readings/index.html.erb
<% content_for :title, "Customer Readings" %>

<%= render partial: 'readings/reading_table', locals: { readings: @readings, customer: @customer } %>

<%= link_to "Customer Homepage", customers_path %>

app/views/readings/new.html.erb
<% content_for :title, 'New Reading' %>

<%= render partial: 'readings/reading_table', locals: { readings: @readings, customer: @customer } %>

<%= form_with model: @reading, url: customer_readings_path, class: :vertical_content do |form| %>
  <%= form.text_field :reading, placeholder: ">= #{number_with_precision(@newest_read, precision: @customer.address.meter_decimal_places)}" %>
  <%= form.submit %><br>
<% end %>