config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'welcome#index'
  get '/settings', to: 'welcome#settings'

  get '/customer_login', to: 'sessions#customer_login_page'
  post '/customer_login', to: 'sessions#customer_login'
  get '/admin_login', to: 'sessions#admin_login_page'
  post '/admin_login', to: 'sessions#admin_login'
  delete '/logout', to: 'sessions#destroy'

  resources :customers, only: %i(index new create) do
    resources :readings, only: %i(index new create)
  end

  resources :admins, only: %i(index)

  namespace :admin do
    resources :customers, only: %i(index show update) do
      post '/invoice', to: "customers#mail"
      resources :readings, only: %i(index new create)
    end
    resources :addresses, only: %i(index new create)
    resources :prices, only: %i(new create)
  end

  root 'welcome#index'
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :address
  has_many :readings
  has_many :readings, as: :read_by
  before_save :email_downcase

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, length: { maximum: 50 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/ }
  validates :address, presence: true

  private

  def email_downcase
    email.downcase!
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < AdminsController
  def index
    @admin ||= current_admin
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
    @address = @customer.address
  end

  def update
    begin
      @customer = UpdateCustomer.new(params[:id], customer_params).call
      @address = UpdateAddress.new(@customer, address_params).call
      Address.transaction do
        @address.save!
        @customer.save!
      end
    rescue ActiveRecord::RecordInvalid
      if @address.errors.any?
        flash[:error] = BuildErrorMessage.new(@address).call
      elsif @customer.errors.any?
        flash[:error] = BuildErrorMessage.new(@customer).call
      end
    end
    redirect_to admin_customers_url
  end

  def mail
    @customer = Customer.find(params[:customer_id])
    @price = Price.last.price
    @used_energy = calculate_usage(@customer)

    InvoiceMailer.with(customer: @customer, price: @price, used_energy: @used_energy).monthly_invoice.deliver_now

    redirect_to admin_customers_url
  end

  private

  def customer_params
    params.require(:customer).permit(%i[first_name last_name email])
  end

  def address_params
    params.require(:address).permit(%i[street street_number unit suburb town zip_code icp meter_decimal_places status])
  end

  def calculate_usage(customer)
    readings = Reading.where(customer: customer).last(2)
    if readings.size == 2
      readings.last.reading - readings.first.reading
    else
      readings.first.reading
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :require_login, only: :index

  def index
    @customer ||= current_customer
  end

  def new
    @address = Address.new
    @customer = Customer.new
  end

  def create
    begin
      @address = BuildAddress.new(address_params).call
      @customer = @address.build_customer(customer_params)
      Address.transaction do
        @address.save!
        @customer.save!
        log_customer_in @customer
        redirect_to customers_url and return
      end
    rescue ActiveRecord::RecordInvalid
      if @address.errors.any?
        flash[:error] = BuildErrorMessage.new(@address).call
      elsif @customer.errors.any?
        flash[:error] = BuildErrorMessage.new(@customer).call
      end
    end
    redirect_to new_customer_path
  end

  private

  def require_login
    unless customer_logged_in?
      flash[:error] = 'Not logged in.'
      redirect_to root_url
    end
  end

  def customer_params
    params.require(:customer).permit(%i[first_name last_name email address_id])
  end

  def address_params
    params.require(:address).permit(%i[street street_number unit suburb town zip_code country icp])
  end
end

app/views/admin/customers/_admin_customer_table.html.erb
<table>
  <tr>
    <th>ID</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Address ID</th>
    <th>Readings</th>
    <th>Editor</th>
    <th>Send Invoice</th>
  </tr>
  <% customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= customer.first_name %></td>
      <td><%= customer.last_name %></td>
      <td><%= customer.email %></td>
      <td><%= link_to "#{customer.address_id}", admin_addresses_path %></td>
      <td><%= link_to 'Readings', admin_customer_readings_path(customer) %></td>
      <td><%= link_to 'Edit', admin_customer_path(customer) %>
      <td><%= link_to 'Invoice', admin_customer_invoice_path(customer), method: :post %></td>
    </tr>
  <% end %>
</table>

app/views/admin/customers/index.html.erb
<% content_for :title, "Customers" %>

<%= render partial: 'admin/customers/admin_customer_table', locals: { customers: @customers } %>

<%= link_to "Admin Homepage", admins_path %>

app/views/admin/customers/show.html.erb
<% content_for :title, "Customer Editor" %>

<%= form_with model: @customer, url: admin_customer_url, class: :vertical_content, local: true do |customer_form| %>
  First Name: <%= customer_form.text_field :first_name %><br>
  Last Name: <%= customer_form.text_field :last_name %><br>
  Email: <%= customer_form.text_field :email %><br>

  <%= fields_for @address, local: true do |address_form| %>
    Street Number: <%= address_form.text_field :street_number %><br>
    Street: <%= address_form.text_field :street %><br>
    Unit: <%= address_form.text_field :unit %><br>
    Suburb: <%= address_form.text_field :suburb %><br>
    Town: <%= address_form.text_field :town %><br>
    Zip Code: <%= address_form.text_field :zip_code %><br>
    ICP Number: <%= address_form.text_field :icp %><br>
    Decimal Places: <%= address_form.text_field :meter_decimal_places %><br>
    Status: <%= address_form.text_field :status %><br>
  <% end %>

  <%= customer_form.submit %><br>
<% end %>